# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/krushang/VLSI/image_processing/image_processing/image_processing.cache/wt [current_project]
set_property parent.project_path D:/krushang/VLSI/image_processing/image_processing/image_processing.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/krushang/VLSI/HDL-main/Image_Processing_Basys3/IMAGE_PROCESSING_BASYS3.ip_user_files/sim_scripts/xsim/flower.coe
add_files -quiet D:/krushang/VLSI/image_processing/image_processing/image_processing.runs/image_synth_1/image.dcp
set_property used_in_implementation false [get_files D:/krushang/VLSI/image_processing/image_processing/image_processing.runs/image_synth_1/image.dcp]
read_verilog -library xil_defaultlib D:/krushang/VLSI/image_processing/image_processing/vga_syncINDEX.v
catch { write_hwdef -file vga_syncIndex.hwdef }
synth_design -top vga_syncIndex -part xc7a35tcpg236-1
write_checkpoint -noxdef vga_syncIndex.dcp
catch { report_utilization -file vga_syncIndex_utilization_synth.rpt -pb vga_syncIndex_utilization_synth.pb }
